version: "3"
services:
  apache:
    build: .
    container_name: php
    restart: always
    ports:
      - '80:80'
    volumes:
      - ./:/var/www/html
    depends_on:
      - db
    links:
      - db
  db:
    image: mysql
    ports: 
      - "3306:3306"
    environment:
      MYSQL_DATABASE: new_test
      MYSQL_USER: user
      MYSQL_PASSWORD: 123456
      MYSQL_ROOT_PASSWORD: 123456
    volumes:
      - ./dump:/docker-entrypoint-initdb.d
      - persistent:/var/lib/mysql
    networks:
      - default
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links: 
      - db:db
    ports:
      - 8080:80
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: 123456
      MYSQL_ROOT_PASSWORD: 123456
volumes:
  persistent: